Ron:

Would you be able to assist me with expressing a bivariate multilevel mediated model in matrix notation? 

The model consists of two mediated models. Four equations in total: two regression equations ($y1$ and $y2$) and two mediated equations ($m1$ and $m2$). $y1$ is radial bone properties,  $y2$ is tibial bone properties, $m1$ is grip strength and $m2$ is knee strength. $Z$ and $W$ are exogenous variables. Grip strength mediates the effects of $W$ on radial bone properties and knee strength mediates the effect of $W$$ on tibial bone properties. 

All equations includes include random-individual effects; $\gamma_i$ in the regression equations and $\delta_i$ in the mediated equations. The random-individual effects are correlated across the regression and mediated equations (i.e., correlated random effects models). The regression equation residuals are correlated, and the mediation equations are corrected (i.e., seemingly unrelated models). 

The base specification restricts the coefficients to equal across the regression equations and mediated equations, respectively. Without matrices the models can be expressed as:

$$ 
y1_{i,t} = \beta_0 + \beta_1 m1_{i,t} + \Theta Z_{i,t}' \Theta + \gamma_{i} + \epsilon1_{i,t} 
$$

$$
m1_{i,t} = \Omega W_{i,t} + \delta_{i} + \mu1_{i,t} 
$$

$$ 
y2_{i,t} = \beta_0 + \beta_1 m2_{i,t} + \Theta Z_{i,t}' \Theta + \gamma_{i} + \epsilon2_{i,t} 
$$

$$ 
m2_{i,t} = \Omega W_{i,t} + \delta_{i} + \mu2_{i,t} 
$$

$$ 
\Sigma = 
\begin{bmatrix}
 \sigma^2_{\epsilon1} & \sigma_{\epsilon1, \epsilon2}  \\
 \sigma_{\epsilon2, \epsilon1} & \sigma^2_{\epsilon2}  \\
\end{bmatrix} 
$$

$$ 
\Sigma = 
\begin{bmatrix}
 \sigma^2_{\mu1} & \sigma_{\mu1, \mu2}  \\
 \sigma_{\mu2, \mu1} & \sigma^2_{\mu2}  \\
\end{bmatrix} 
$$

$$
\Sigma = 
\begin{bmatrix}
 \sigma^2_{\gamma} & \sigma_{\gamma, \delta}  \\
 \sigma_{\delta, \gamma} & \sigma^2_{\delta}  \\
\end{bmatrix} 
$$

I would like to express the entire model using matrices: $\mathbf{Y}$ represents both $y1_{i,t}$ and $y2_{i,t}$ and $\mathbf{M}$ represents both $m1_{i,t}$ and $m2_{i,t}$. Make sense?

## Ron's response

Double click and type

In [1]:
import pandas
import ipystata
from ipystata.config import config_stata
config_stata('/usr/local/stata/stata-mp')

pandas.set_option('display.float_format', lambda x: '%.2f' % x)
pandas.set_option('max_columns', 200)
pandas.set_option('max_rows', 400)
pandas.set_option('max_colwidth', 150)
pandas.set_option('mode.sim_interactive', True)
pandas.set_option('colheader_justify', 'center')

IPyStata is loaded in batch mode.

In [2]:
dm = pandas.read_csv('out/data_analysis.csv')
dm.head()

,ID,Sequence,calo,height,weight,Godin_PA,id,season,session,gender,rsos,tsos,grip,ptiso,biodex,matlab,ntxc,matu,mvh,age,Exclusion,NoSOS,NoGrip,Noptiso,Nontx,Nomvh,T,_o,_id,_v,size,_season,omit,boys,girls,trip,st_rsos,st_tsos,st_grip,st_ptiso,st_biodex,st_matlab,st_ntxc,st_calo,st_matu,st_mvh,st_age,st_height,st_weight,st_Godin_PA
0,100,1,1572.00,152.00,44.20,37.00,100,spring,1,boy,3828,3601,nan,113.93,129.10,113.93,711.85,-1.67,105.71,11.75,none,nan,Not taken sequence 1,NaN,NaN,NaN,NaN,1,1,1,4.00,spring,nan,1,0,1,0.12,-0.79,nan,-0.25,-0.04,-0.25,0.65,-0.04,-0.40,-0.03,-0.05,-0.01,-0.13,-0.93
1,100,3,2219.01,160.80,48.80,48.00,100,spring,3,boy,3898,3629,27.00,136.02,138.70,136.02,760.09,-0.71,93.62,12.71,none,nan,NaN,NaN,NaN,NaN,NaN,2,1,2,nan,NaN,nan,1,0,2,0.82,-0.53,0.48,0.14,0.13,0.14,0.84,1.30,0.07,-0.32,0.44,0.64,0.19,-0.65
2,100,5,2599.83,173.30,63.50,44.00,100,spring,5,boy,3851,3677,37.00,177.05,178.00,177.05,543.73,0.41,98.14,13.83,none,nan,NaN,NaN,NaN,NaN,NaN,3,1,3,nan,NaN,nan,1,0,3,0.35,-0.10,1.83,0.86,0.81,0.86,0.01,2.10,0.63,-0.21,1.00,1.55,1.20,-0.75
3,100,7,2482.12,177.40,67.30,66.00,100,spring,7,boy,3952,3740,40.50,205.80,205.80,205.80,454.36,1.17,88.14,14.74,none,nan,NaN,NaN,NaN,NaN,NaN,4,1,4,nan,NaN,nan,1,0,4,1.36,0.48,2.31,1.37,1.29,1.37,-0.32,1.85,1.00,-0.46,1.46,1.85,1.47,-0.20
4,101,1,1549.99,158.10,47.30,25.00,101,spring,1,boy,3682,3603,nan,133.05,139.10,133.05,938.00,-1.63,89.29,11.45,none,nan,Not taken sequence 1,NaN,NaN,NaN,NaN,5,2,1,1.00,spring,nan,1,0,1,-1.34,-0.77,nan,0.09,0.13,0.09,1.51,-0.09,-0.38,-0.43,-0.20,0.44,0.08,-1.23

In [3]:
%%stata --data dm 

rename biodex biod
gen lng = ln(grip)
gen lnb = ln(biod)
gen lnr = ln(rsos)
gen lnt = ln(tsos)

rename st_rsos r
rename st_tsos t
rename st_grip g
rename st_biod b
rename st_matu m
rename st_ntxc n
rename st_calo c
rename st_mvh v

gen rb = boys * r
gen rg = girls * r

set cformat %9.4f

#delimit ;

eststo m1: gsem
    (r <- g@k1   _cons@kk)
    (t <- b@k1 v _cons@kk)
    (r <- m@k2 n@k3  M1[id]@1 _cons@cc) 
    (g b <- m@k4 c@k5 M2[id]@1), 
    covstruct(_lexogenous, diagonal)   
    nocapslatent latent(M1 M2) 
    cov(e.r*e.t) cov(e.g*e.b) cov(M1[id]*M2[id])
    nohead nolog 
    ;

(43 missing values generated)
delimiter now ;>     (r <- g@k1   _cons@kk)
>     (t <- b@k1 v _cons@kk)
>     (r <- m@k2 n@k3  M1[id]@1 _cons@cc)
>     (g b <- m@k4 c@k5 M2[id]@1),
>     covstruct(_lexogenous, diagonal)
>     nocapslatent latent(M1 M2)
>     cov(e.r*e.t) cov(e.g*e.b) cov(M1[id]*M2[id])
>     nohead nolog
>     ;
 ( 1)  [r]g - [t]b = 0
 ( 2)  [r]M1[id] = 1
 ( 3)  [g]m - [b]m = 0
 ( 4)  [g]c - [b]c = 0
 ( 5)  [g]M2[id] = 1
 ( 6)  [b]M2[id] = 1
-----------------------------------------------------------------------------------
                  |      Coef.   Std. Err.      z    P>|z|     [95% Conf. Interval]
------------------+----------------------------------------------------------------
r <-              |
                g |     0.3333     0.0490     6.80   0.000       0.2373      0.4293
                m |     0.0913     0.0534     1.71   0.087      -0.0133      0.1960
                n |    -0.1911     0.0444    -4.30   0.000      -0.2781     -0.1041
                  |
           M1[id] |     1.0000  (constrained)
                  |
            _cons |    -0.0136     0.0612    -0.22   0.825      -0.1334      0.1063
------------------+----------------------------------------------------------------
t <-              |
                b |     0.3333     0.0490     6.80   0.000       0.2373      0.4293
                v |    -0.1075     0.0520    -2.07   0.039      -0.2094     -0.0056
            _cons |    -0.0825     0.0517    -1.60   0.111      -0.1838      0.0189
------------------+----------------------------------------------------------------
g <-              |
                m |     0.6284     0.0324    19.39   0.000       0.5649      0.6919
                c |     0.0815     0.0270     3.02   0.003       0.0285      0.1344
                  |
           M2[id] |     1.0000  (constrained)
                  |
            _cons |    -0.0062     0.0540    -0.12   0.908      -0.1121      0.0996
------------------+----------------------------------------------------------------
b <-              |
                m |     0.6284     0.0324    19.39   0.000       0.5649      0.6919
                c |     0.0815     0.0270     3.02   0.003       0.0285      0.1344
                  |
           M2[id] |     1.0000  (constrained)
                  |
            _cons |     0.0304     0.0503     0.60   0.545      -0.0681      0.1289
------------------+----------------------------------------------------------------
       var(M1[id])|     0.4438     0.0693                        0.3268      0.6028
       var(M2[id])|     0.3586     0.0470                        0.2774      0.4636
------------------+----------------------------------------------------------------
cov(M2[id],M1[id])|    -0.0725     0.0442    -1.64   0.101      -0.1592      0.0143
------------------+----------------------------------------------------------------
          var(e.r)|     0.3175     0.0403                        0.2475      0.4073
          var(e.t)|     0.8050     0.0663                        0.6850      0.9461
          var(e.g)|     0.2834     0.0283                        0.2330      0.3447
          var(e.b)|     0.1591     0.0169                        0.1293      0.1959
------------------+----------------------------------------------------------------
      cov(e.t,e.r)|     0.2557     0.0552     4.63   0.000       0.1475      0.3638
      cov(e.b,e.g)|     0.0379     0.0139     2.72   0.006       0.0106      0.0651
-----------------------------------------------------------------------------------
>

end of do-file